# Generated by Django 3.1.7 on 2022-03-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/user-imgs/'),
        ),
    ]
