# Generated by Django 3.1.7 on 2022-03-07 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customusers_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('customusers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.customusers')),
            ],
            options={
                'verbose_name': 'admin',
                'verbose_name_plural': 'admins',
            },
            bases=('users.customusers',),
        ),
    ]
