# Generated by Django 3.1.7 on 2022-03-14 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='end',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='start',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='date_joined',
        ),
    ]
