# Generated by Django 3.1.7 on 2021-05-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210505_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='type',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(db_index=True, default='1', max_length=25, unique=True),
        ),
    ]
