# Generated by Django 3.1.7 on 2022-03-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220314_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='username',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
