# Generated by Django 3.1.7 on 2021-05-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210505_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='email_address',
        ),
    ]
