# Generated by Django 3.1.7 on 2021-08-23 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstructors',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.batch'),
        ),
    ]
