# Generated by Django 3.1.7 on 2021-05-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_courseinstructors_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstructors',
            name='end',
            field=models.DateField(null=True),
        ),
    ]
