# Generated by Django 3.1.7 on 2021-08-28 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('core', '0004_auto_20210823_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.instructor'),
        ),
    ]
