# Generated by Django 3.1.7 on 2021-05-05 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210505_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstructors',
            name='batch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.batch'),
        ),
    ]
