# Generated by Django 3.1.7 on 2022-03-11 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_admin'),
        ('core', '0006_auto_20220305_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstructors',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_details', to='users.instructor'),
        ),
    ]
