# Generated by Django 3.1.7 on 2021-05-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210505_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'batches'},
        ),
        migrations.AddField(
            model_name='batch',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
