# Generated by Django 3.1.7 on 2022-03-14 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220311_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinstructors',
            name='end',
        ),
        migrations.RemoveField(
            model_name='courseinstructors',
            name='start',
        ),
    ]
