# Generated by Django 3.1.7 on 2021-05-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210505_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
