# Generated by Django 3.1.7 on 2021-08-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_instructor_email_address'),
        ('core', '0015_auto_20210814_1156'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('date', 'course', 'student')},
        ),
    ]
